/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserBook struct {

	UserId int64 `json:"user_id"`

	BookId int64 `json:"book_id"`
	// 読書ステータス
	Status string `json:"status"`

	Memo string `json:"memo,omitempty"`
}
