/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Book struct {

	Id int64 `json:"id"`

	Title string `json:"title"`

	Description string `json:"description,omitempty"`

	Image string `json:"image,omitempty"`

	Isbn10 string `json:"isbn_10,omitempty"`

	Isbn13 string `json:"isbn_13,omitempty"`

	PageCount int32 `json:"page_count"`

	PublishedAt string `json:"published_at"`
}
