/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserBooksPageCount struct {

	Id int64 `json:"id,omitempty"`

	PageCount int32 `json:"page_count,omitempty"`

	PublishedAt string `json:"published_at,omitempty"`
}
