/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"BooksSearchPost",
		strings.ToUpper("Post"),
		"/books/search",
		BooksSearchPost,
	},

	Route{
		"SigninPost",
		strings.ToUpper("Post"),
		"/signin",
		SigninPost,
	},

	Route{
		"SignupPost",
		strings.ToUpper("Post"),
		"/signup",
		SignupPost,
	},

	Route{
		"BooksPost",
		strings.ToUpper("Post"),
		"/books",
		BooksPost,
	},

	Route{
		"UserbooksValuePost",
		strings.ToUpper("Post"),
		"/userbooks/value",
		UserbooksValuePost,
	},

	Route{
		"UsersUserIdBooksGet",
		strings.ToUpper("Get"),
		"/users/{userId}/books",
		UsersUserIdBooksGet,
	},
}
