/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	// UserBook Id
	Id int32 `json:"id,omitempty"`
	// UserBook Name
	Name string `json:"name,omitempty"`
}
