/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccessToken struct {

	AccessToken string `json:"access_token,omitempty"`

	ExpiresIn string `json:"expires_in,omitempty"`

	RefreshToken string `json:"refresh_token,omitempty"`
}
