/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserBooksList struct {

	Userbooks []UserBook `json:"userbooks,omitempty"`

	Books []Book `json:"books,omitempty"`
}
