/*
 * Stacked Books API
 *
 * これはStacked BooksのAPI定義です。
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {

	Id int64 `json:"id"`

	Name string `json:"name"`

	Email string `json:"email"`

	Password string `json:"password"`

	Avatar string `json:"avatar,omitempty"`

	Role string `json:"role"`
}
